Декоративные элементы на главной странице
htmlacademy-htmlcss/1633211-technomart-30 pull request #11
Opened 2021-02-24 13:40 UTC by kganzh

2021-02-25 06:53 UTC, Dima-Dim requested changes

2021-02-25 06:53 UTC, Dima-Dim commented on css/style.css
> +  left: 17px;
Не нужно так делать для элементов которые находятся в потоке. Для этого у нас есть довольно много более очевидных свойств, таких как внешние и внутренние отступы, позиционирование внутри flex и grid контейнеров.

2021-02-25 06:53 UTC, Dima-Dim commented on css/style.css
> +  background-image: url("/img/icons/icons_header-footer/icon-bookmark.svg");
`/img/icons/icons_header-footer/icon-bookmark.svg` -> `../img/icons/icons_header-footer/icon-bookmark.svg` и для других путей к изображениям в css так же нужно сделать.

2021-02-25 06:53 UTC, Dima-Dim commented on css/style.css
> +.demo-block__item.item-demo h3::after {
Это должен быть псевдоэлемент не заголовка, а самой карточки.

2021-02-25 06:53 UTC, Dima-Dim commented on css/style.css
> +  position: absolute;
Можно оставить в потоке спозиционировав внутри элемента к которому оно относится.

2021-02-28 12:06 UTC, Dima-Dim commented on css/style.css
> +  max-height: 42px;
Фиксирует максимальную высоту и создает проблемы при переполнении.

2021-02-28 12:06 UTC, Dima-Dim commented on css/style.css
> +  box-shadow: inset 0px -5px 0px rgba(0, 0, 0, 0.24);
Мы же хотим, чтобы тень была наружи? Почему тогда inset?

2021-02-28 14:22 UTC, kganzh commented
В шапке хедера все исправила. Но по высоте она почему то все равно не устанавливается в 42px. Выходит за 44px примерно. https://prnt.sc/109db2g  Вот здесь видно

2021-03-01 06:52 UTC, Dima-Dim commented
> В шапке хедера все исправила. Но по высоте она почему то все равно не устанавливается в 42px. Выходит за 44px примерно. https://prnt.sc/109db2g Вот здесь видно
Идёшь по всем внутренним элементам и ищешь кто раздвигает контейнер на 44px.

2021-03-03 13:29 UTC, merged