Разметила главную страницу
htmlacademy-htmlcss/1633211-technomart-30 pull request #2
Opened 2021-01-23 15:46 UTC by kganzh

- Разметила **index.html**

- Создала страницы:
**catalog.html**
**blank.html**

2021-01-24 07:15 UTC, Dima-Dim requested changes
В целом хорошо, есть ряд лишних тегов, оставил комментарии к коду. Есть однотипные проблемы, не стал их все помечать одинаковыми замечаниями.

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +          <span>Закладки:</span>
span-а для значения, которое идёт далее должно быть достаточно, а этот может попасть под https://up.htmlacademy.ru/htmlcss/30/criteries#d2

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +        <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
Почему i?

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +          <a href="tel:+78125550555"><span>+7 (812) 555-05-55</span></a><br>
Для чего span?
Для чего br?

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +          <h2>Каталог</h2>
Нет тут каталога :) Зато есть дополнительные скрытые слайды.

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +            <a href="#">
То что это ссылка однозначно нигде не указано, а то что внутри будут кнопки/ссылкм указано явно. А т.к. интерактивный элемент не может быть внутри интерактивного элемента, то это не ссылка :)

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +                <li><span>32500 Р.</span></li>
Для чего span?

2021-01-24 07:15 UTC, Dima-Dim commented on index.html
> +      <div>
Похоже на лишний тег, как минимум на данном этапе.

2021-01-24 07:55 UTC, kganzh commented on index.html
> +        <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
https://up.htmlacademy.ru/htmlcss/30/book/1.5#s4
Информация из учебника )) скрин: https://prnt.sc/xjekka

Но я бы обернула в тег <p>

2021-01-25 06:10 UTC, Dima-Dim commented on index.html
> +        <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
Спасибо за источник этого недоразумения :) я уточню.

2021-01-25 06:11 UTC, Dima-Dim commented on index.html
> +        <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
Вообще для главной страницы это больше даже похоже на h1, чем на p.

2021-01-25 07:05 UTC, merged