Графика всех страниц
htmlacademy-htmlcss/1633211-technomart-30 pull request #4
Opened 2021-01-27 15:18 UTC by kganzh

---
:mortar_board: [Графика всех страниц](https://up.htmlacademy.ru/htmlcss/30/user/1633211/tasks/4)

:boom: https://htmlacademy-htmlcss.github.io/1633211-technomart-30/4/

2021-01-28 06:45 UTC, Dima-Dim requested changes
icon-1.png и т.п. это вроде как svg, так же как и icon-left.png и т.п.
icons header, footer - совсем нет :) https://up.htmlacademy.ru/htmlcss/30/criteries#b14
Так же перепроверь на этот критерий и остальные названия папок и файлов.

2021-01-28 10:09 UTC, kganzh commented
@Dima-Dim изменила форматы и названия графики. Единственное, не совсем понятно в каком формате должен быть значок "New" на товарах.

2021-01-29 06:33 UTC, Dima-Dim commented
> @Dima-Dim изменила форматы и названия графики. Единственное, не совсем понятно в каком формате должен быть значок "New" на товарах. Сохранила в пнг

Хорошо! Пусть будет в png.

2021-01-29 06:35 UTC, Dima-Dim approved these changes
Обрати внимание на red-list.svg, внутри не svg и возможно получится вовсе обойтись без этого изображения.

2021-01-29 06:35 UTC, merged

2021-01-29 09:25 UTC, kganzh commented
> Обрати внимание на red-list.svg, внутри не svg и возможно получится вовсе обойтись без этого изображения.

точно...