Стилизация главной страницы
htmlacademy-htmlcss/1633211-technomart-30 pull request #5
Opened 2021-01-31 22:35 UTC by kganzh

2021-02-01 07:14 UTC, Dima-Dim requested changes
Не забываем про https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-01 07:14 UTC, Dima-Dim commented on index.html
> +    <link rel="stylesheet" href="css/fonts.css">
https://up.htmlacademy.ru/htmlcss/30/criteries#b2

2021-02-01 07:14 UTC, Dima-Dim commented on index.html
> +          <a class="header-bottom__tel" href="tel:+78125550555"><span>+7 (812) 555-05-55</span></a>
Нам точно нужен span?

2021-02-01 07:14 UTC, Dima-Dim commented on index.html
> +        <figure class="demo-block__slider">
Оптимальнее сделать это списком, потому что это список слайдов.

2021-02-01 07:14 UTC, Dima-Dim commented on index.html
> +            <div class="product-card__front-side">
Точно нужна дополнительная обёртка?

2021-02-01 07:14 UTC, Dima-Dim commented on css/style.css
> +h1 {
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-01 07:14 UTC, Dima-Dim commented on css/style.css
> +  height: 89px;
Вызовет проблемы при переполнении.

2021-02-01 07:14 UTC, Dima-Dim commented on css/style.css
> +  background-color: #161D29;
https://up.htmlacademy.ru/htmlcss/30/criteries#d30

2021-02-01 07:14 UTC, Dima-Dim commented on css/style.css
> +  height: 45px;
Тоже будут проблемы с переполнением.

2021-02-01 13:49 UTC, kganzh commented on index.html
> +          <a class="header-bottom__tel" href="tel:+78125550555"><span>+7 (812) 555-05-55</span></a>
нет, снова убрала ))

2021-02-03 16:24 UTC, Dima-Dim commented on css/style.css
> +  box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.15);
На проверке и к этому цвету без переменной могут придраться :)

2021-02-03 16:24 UTC, Dima-Dim commented on index.html
>            <a class="button slider-link-catalog" href="/catalog.html">Открыть каталог</a>
Эта ссылка относится к конкретному слайду и у каждого слайда она может своя и разная.

2021-02-03 16:24 UTC, Dima-Dim approved these changes

2021-02-03 16:25 UTC, merged